program/app/views/admin.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, session, request,make_response
from app.forms import RegisterForm,AddProduct, UploadForm,UpdatePassword,LoginForm_a,UserInformation,AddUserForm

from app.models import User,Admin,Product
from app.extensions import db, photos
from app.mail import send_mail
from flask_login import login_user, logout_user, login_required, current_user
from PIL import Image
import os

admin = Blueprint('admin', __name__)


# 管理员登陆路由
@admin.route('/login_a/', methods=['GET', 'POST'])
def login_a():
    form = LoginForm_a()
    if form.validate_on_submit():
        if not Admin.query.filter(Admin.username == 'admin'):
            flash('用户名错误')
            return render_template('user/login_a.html', form=form)
        elif Admin.query.filter(Admin.password == '123456'):
            flash('登陆成功')
            return render_template('main/index_a.html', form=form)
    return render_template('user/login_a.html',form=form)


# 退出登录
@admin.route('/logout/')
def logout():
    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))

@admin.route('/comfile_a/')
def comfile_a():
    return render_template('main/comfile_a.html')

#开发部
@admin.route('/project_a/',methods = ['GET','POST'])
def project_a():

    form = AddProduct()
    if form.validate_on_submit():
        p = Product(
            name=form.name.data,
            sections=form.section.data,
            progress=form.progress.data
        )
        db.session.add(p)
        db.session.commit()
    u = User.query.filter(User.section == '开发部').all()
    # pros = Product.query.filter(Product.sections == '开发部')
    pro = Product.query.all()
    return render_template('bumen/project_a.html',u =u,pro = pro,form=form,endpoint='admin.del_product',endpoint1= 'admin.update_progress')
#删除项目
@login_required
@admin.route('/del_product/')
def del_product():
    id = request.args.get('id')
    Product.query.filter(Product.id == id).delete()
    return redirect(url_for('admin.project_a'))

@login_required
@admin.route('/update_progress/')
def update_progress():
    id = request.args.get('id')
    from sqlalchemy.orm import sessionmaker
    from sqlalchemy import create_engine

    ENGINE = create_engine("mysql://root:Root9248*@118.25.43.122:3306/bishe?charset=utf8",
                           convert_unicode=True)
    Session2 = sessionmaker(bind=ENGINE, autocommit=False, autoflush=False)

    session2 = Session2()

    product = session2.query(Product).filter_by(id=id).first()
    if product.progress == '未完成':
        product.progress = "已完成"
        session2.commit()
    else:
        product.progress ='未完成'
        session2.commit()
    return redirect(url_for('admin.project_a'))

@admin.route('/renshibu_a/',methods =['GET','POST'])
def renshi_a():

    form = AddUserForm()
    if form.validate_on_submit():
        # 根据表单数据创建User对象
        u = User( username=form.username.data,
                  password=form.password.data,
                  sex = form.sex.data,
                  age = form.age.data,
                  confirmed = 1,
                  email=form.email.data,
                  idCard=form.idCard.data,
                  phonenumber=form.phonenumber.data,
                  section=form.section.data,
                  part=form.part.data,
                  )
        # 然后保存到数据库中
        db.session.add(u)
        # 此时还没有提交，所以新用户没有id值，需要手动提交
        db.session.commit()



    page = request.args.get('page',1,type=int)
    pagination = User.query.order_by(User.age).paginate(page=page,per_page=3,error_out=False)
    # us = User.query.filter(User.username == '用户测试').first()

    users = pagination.items
    resps =request.cookies.get('name')
    us = User.query.filter(User.username == resps)
    return render_template('bumen/renshi_a.html', us = us,users = users,pagination=pagination,
                           endpoint1 = 'admin.deluser',form =form,endpoint2='admin.select_part',
                           endpoint4='admin.del_absent',
                            endpoint5='admin.add_absent',endpoint6='admin.select_sections')


#删除员工：
@login_required
@admin.route('/deluser/')
def deluser():
    id = request.args.get('id')
    User.query.filter(User.id == id).delete()
    return redirect(url_for('admin.renshi_a'))


@login_required
@admin.route('select_part')
def select_part():
    id= request.args.get('id')
    u = User.query.filter(User.id == id).first()
    if u.part == '员工':
        u.part = '部长'
        db.session.add(u)
        db.session.commit()
    else:
        u.part = '员工'
        db.session.add(u)
        db.session.commit()
    return redirect(url_for('admin.renshi_a'))



@login_required
@admin.route('del_absent')
def del_absent():
    id =request.args.get('id')
    u = User.query.filter(User.id == id).first()
    if u.absent != 0:
        u.absent -= 1
    else:
        u.absent = 0
    db.session.add(u)
    db.session.commit()
    return redirect(url_for('admin.renshi_a'))

@login_required
@admin.route('add_absent')
def add_absent():
    id =request.args.get('id')
    u = User.query.filter(User.id == id).first()
    if u.absent>30:
        u.absent = 0
    else:
        u.absent += 1
    db.session.add(u)
    db.session.commit()
    return redirect(url_for('admin.renshi_a'))

@login_required
@admin.route('add_select_sections')
def select_sections():
    id =request.args.get('id')
    u = User.query.filter(User.id == id).first()
    if u.section==None:
        u.section='开发部'
    elif u.section == '开发部':
        u.section='后勤部'
    elif u.section == '后勤部':
        u.section='开发部'
    db.session.add(u)
    db.session.commit()

    return redirect(url_for('admin.renshi_a'))

program/app/views/main.py
from flask import Blueprint, render_template,flash,redirect,url_for
# from app.forms import PostsForm
from flask_login import current_user
from app.models import Admin
from app.extensions import db
main = Blueprint('main', __name__)

#
# @main.route('/',methods =['POST','GET'])
# def index():
#     form = PostsForm()
#
#     if form.validate_on_submit():
#         if current_user.is_authenticated:
#             #创建post对象，导入表单库
#             u = current_user._get_current_object()
#             p =Posts(content=form.content.data,user =u)
#             db.session.add(p)
#             flash('发表成功')
#             return redirect(url_for('main.index'))
#         else:
#             flash('登录后才能发表')
#             return redirect(url_for('user.login'))
#     return render_template('main/index.html',form = form)
@main.route('/')
def index():
    return render_template('main/index.html')

@main.route('/admin/')
def index_a():

    return render_template('main/index_a.html')

@main.route('/head/')
def index_h():
    return render_template('main/index.html')

program/app/views/user.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, session, request,make_response
from app.forms import RegisterForm, LoginForm, UploadForm,UpdatePassword,LoginForm_a,UserInformation

from app.models import User,Admin,Product
from app.extensions import db, photos
from app.mail import send_mail
from flask_login import login_user, logout_user, login_required, current_user
from PIL import Image
import os


user = Blueprint('user', __name__)


@user.route('/test/')
@login_required
def test():
    return 'xxxxx'


# 退出登录
@user.route('/logout/')
def logout():

    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))

#普通用户登陆路由
@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('无效的用户名')
            # return redirect(url_for("user.login"))
        elif not u.confirmed:
            flash('账户尚未激活，请激活后再登录')
            # return redirect(url_for("user.login"))
        elif u.verify_password(form.password.data):

            # 用户登录，顺便可以完成记住我的功能，还可以指定有效时间
            login_user(u, remember=form.remember.data)
            flash('登录成功')


            return redirect(request.args.get('next') or url_for('main.index'))


        else:
            flash('无效的密码')

    return render_template('user/login.html', form=form)


#普通用户注册路由
@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 根据表单数据创建User对象
        u = User( username=form.username.data,
                  password=form.password.data,
                  sex = form.sex.data,
                  age = form.age.data,
                  email=form.email.data,
                  idCard=form.idCard.data,
                  phonenumber=form.phonenumber.data,

                  )

        # 然后保存到数据库中
        db.session.add(u)
        # 此时还没有提交，所以新用户没有id值，需要手动提交
        db.session.commit()
        # 准备token
        # 发送激活邮件
        token = u.generate_activate_token()
        url = url_for('user.activate', token=token, _external=True)
        send_mail(form.email.data, '账户激活', 'activate', username=form.username.data, url=url)
        flash('激活邮件已发送至您的邮箱，请点击连接以完成激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)




# @user.route('/login_a/')
# def login_a():
# ##管理员登陆
#             if u.part == 0:
#                 flash('登陆成功')
#                 return render_template('user/login_a.html',form = form)

#激活路由
@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash('激活成功，请等待公司对您进行部门分配')
        return redirect(url_for('user.login'))
    else:
        flash('激活失败')
        return redirect(url_for('main.index'))




# 用户详情

@user.route('/profiles/',methods = ['GET','POST'])
@login_required
def profiles():
    form = UserInformation()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.name.data).first()
        if current_user.username != form.name.data:
            flash('用户名不能修改')
            return redirect(url_for('user.profiles'))
        u.sex = form.sex.data
        u.age = form.age.data
        # try:
        u.idCard= form.idCard.data
        # except:u.idCard.
        u.phonenumber=form.phonenumber.data
        u.section =form.section.data
        db.session.add(u)
        db.session.commit()
        #设置cookie值记录
        resp = redirect(url_for('user.profile'))
        resp.set_cookie('name',u.username)
        return resp
    print("dsadasda")
    return render_template('user/profiles.html',form=form)





@user.route('/profile/')
@login_required
def profile():
    s = current_user.username
    u = User.query.filter(User.username == s).first()
    try:
        idcard = u.idCard
        phonenumber = u.phonenumber
        sex = u.sex
        age = u.age

    except:
        idcard = None
        phonenumber = None
        sex = None
        age = None
    img_url = photos.url(current_user.icon)
    return render_template('user/profile.html', img_url=img_url,name = s,sex = sex,age = age,idcard = idcard,phonenumber = phonenumber)





# 上传头像
@user.route('/change_icon/', methods=['GET','POST'])
def change_icon():
    form = UploadForm()
    if form.validate_on_submit():
        # 获取后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 随机文件名
        filename = random_string() + suffix
        photos.save(form.icon.data, name=filename)
        # 生成缩略图
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        img = Image.open(pathname)
        img.thumbnail((128, 128))
        img.save(pathname)
        # 删除原来的头像(不是默认头像时才需要删除)
        if current_user.icon != 'default.jpeg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon))
        # 保存到数据库
        current_user.icon = filename
        db.session.add(current_user)
        return redirect(url_for('user.change_icon'))
    img_url = photos.url(current_user.icon)
    return render_template('user/change_icon.html', form=form, img_url=img_url)






def random_string(length=32):
    import random
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(random.choice(base_str) for i in range(length))

#公司简介
@user.route('/com_file/')
def com_file():
    return render_template('main/com_file.html')




#开发部
@user.route('/kaifabu/', methods = ['GET','POST'])
def kaifa():
    if current_user.is_authenticated:
        if current_user.section != '开发部':
            flash('您不属于开发部')
            return redirect(url_for('main.index'))
        if current_user.part  == '部长':
            u = User.query.filter(User.section == '开发部')
            #增加新项目
            if request.method == "POST":
                add_b = request.form.get('add')
                add_product = Product(
                    name = add_b,
                    progress='未完成',
                    sections='开发部',
                )
                if Product.query.filter(Product.name==add_b).first():
                    flash('此项目已经存在，请增加新项目')
                    return render_template('bumen/kaifa_b.html')
                db.session.add(add_product)
                db.session.commit()
            p = Product.query.filter(Product.user == None)
            pro = Product.query.all()
            return render_template('bumen/kaifa_b.html',u= u,p_b =pro,p=p)

        #普通员工操作：
        u = User.query.filter(User.username == current_user.username).first()
        # pro_u = u.u_project.all()
        p = u.u_project.all()
        print('**************************')
        print(type(u))
        #获取未完成项目
        pro = Product.query.filter(Product.progress == '未完成')
        pro_unend = []
        for i in pro:
            a = i.user.all()
            b = []
            if a!= []:
                for j in a:
                    b.append(j.username)
                    if current_user.username not in b:
                       pro_unend.append(i)
            else:
                if i not in pro_unend:
                    pro_unend.append(i)
        # 获取个人未完成项目
        pro_end = []
        for i in p:
            if i.progress == '未完成':
                pro_end.append(i)
        # return pro_end
        #查询个人所有项目

        #获取数据
        if request.method == 'POST':
            #增加项目
            add_pro_id = request.form.get('add_pro')
            print(add_pro_id)
            u = User.query.get(current_user.id)

            add_pro = Product.query.get(int(add_pro_id))


            u.u_project.append(add_pro)

            db.session.add(u)

        return render_template('bumen/kaifa.html', p=p, pro_end = pro_end , pro_unend=pro_unend,endpoint='user.updatepro')

    flash('您还没有登陆，请登陆后进入')
    return redirect(url_for('user.login'))

@login_required
@user.route('/updatepro/')
def updatepro():

    finish_pros = request.args.get('id')
    # print('!!!!!!!!!!!!!!!!!!!!!!!!!')
    print(finish_pros)
    from sqlalchemy.orm import sessionmaker
    from sqlalchemy import create_engine

    ENGINE = create_engine("mysql://root:Root9248*@118.25.43.122:3306/bishe?charset=utf8",
                           convert_unicode=True)
    Session2 = sessionmaker(bind=ENGINE, autocommit=False, autoflush=False)

    session2 = Session2()

    product = session2.query(Product).filter_by(id=int(finish_pros)).first()
    product.progress = "已完成"
    session2.commit()

    return redirect(url_for('user.kaifa'))


#人事部
@user.route('/renshibu/',methods = ['GET','POST'])
def renshi():

    if current_user.is_authenticated:
        if current_user.section != '人事部':
            flash('您不属于人事部')
            return redirect(url_for('main.index'))
        if current_user.part == '部长':
            # user = User.query.filter(User.section != None)
            page = request.args.get('page', 1, type=int)
            pagination = User.query.filter(User.section != None).order_by(User.age).paginate(page=page, per_page=3, error_out=False)


            user = pagination.items
            pagination2 =User.query.filter(User.section == None).order_by(User.age).paginate(page=page, per_page=3, error_out=False)
            nosec_user = pagination2.items
            return render_template('bumen/renshi_b.html',pagination=pagination,pagination2=pagination2,
                                   user= user,nosec_user = nosec_user,endpoint2='user.del_absent',
                                   endpoint3='user.add_absent',endpoint4='user.select_section')
        #未分配部门员工分配部门


        page = request.args.get('page', 1, type=int)
        pagination3 = User.query.filter(User.section != None).order_by(User.age).paginate(page=page, per_page=3,
                                                                                         error_out=False)

        users = pagination3.items

program/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title%}默认标题{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('user.kaifa') }}">开发部</a></li>
                    <li><a href="{{ url_for('user.renshi') }}">人事部</a></li>
                    <li><a href="{{ url_for('user.houqin') }}">后勤部</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">{{ current_user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('user.profile') }}">用户信息</a></li>
                                <li><a href="{{ url_for('user.update_password') }}">修改密码</a></li>
                                <li><a href="{{ url_for('user.profiles') }}">修改信息</a></li>
                                <li><a href="{{ url_for('user.change_icon') }}">上传头像</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">登陆<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li ><a href="{{ url_for('user.login') }}">
                                    普通用户登陆</a>
                                </li>
                                <li><a href="{{ url_for('admin.login_a') }}">
                                       管理员登陆</a>
                                </li>
                            </ul>
                        </li>

                        <li class="collapse navbar-collapse">
                            <a href="{{ url_for('user.register') }}">注册<span class="caret"></span></a>
                        </li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}默认内容{% endblock %}
    </div>
{% endblock %}

program/app/templates/common/base_a.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title%}默认标题{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index_a') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('admin.project_a') }}">项目管理</a></li>
                    <li><a href="{{ url_for('admin.renshi_a') }}">人事管理</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('admin.logout') }}">退出</a></li>
                        <li><a href="#">您好！</a></li>
{#                        <li class="dropdown">#}
{#                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"#}
{#                               aria-haspopup="true" aria-expanded="false">{{ name }}<span class="caret"></span></a>#}
{#                            <ul class="dropdown-menu">#}
{#                                <li><a href="{{ url_for('user.profile_a') }}">用户详情</a></li>#}
{#                                <li><a href="{{ url_for('user.update_password_a') }}">修改密码</a></li>#}
{#                                <li><a href="{{ url_for('user.profiles_a') }}">修改信息</a></li>#}
{#                                <li><a href="{{ url_for('user.change_icon') }}">上传头像</a></li>#}
{#                            </ul>#}
{#                        </li>#}
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">登陆<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li ><a href="{{ url_for('user.login') }}">
                                    普通用户登陆</a>
                                </li>
                                <li><a href="{{ url_for('admin.login_a') }}">
                                       管理员登陆</a>
                                </li>
                            </ul>
                        </li>

                         <li class="collapse navbar-collapse">
                            <a href="{{ url_for('user.register') }}">注册<span class="caret"></span></a>
                        </li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}默认内容{% endblock %}
    </div>
{% endblock %}

program/app/templates/common/macros.html
  {% macro pagination_show(pagination, endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页 #}
            <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {#  中间页码 #}

            {% for p in pagination.iter_pages() %}
                {% if p %}
                    <li {% if p == pagination.page %}class="active"{% endif %}><a href="{% if p == pagination.page %}#{% else %}{{ url_for(endpoint, page=p, **kwargs) }}{% endif %}">{{ p }}</a></li>
                {% else %}
                    {# 显示不完会返回None，需要显示成... #}
                    <li><a href="#">&hellip;</a></li>
                {% endif %}
            {% endfor %}

            {# 下一页 #}
            <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}